### PR TITLE
Change the outdated emphasis block into the current theme

### PR DESCRIPTION
**Pull request by srcres258**
The "!!! important" usage within the documentation is used within the Forge epoch, however NeoForge turned to use a novel format for these highlighted paragraphs. Hence make up for the missed one.

------------------
Preview URL: https://pr-60.neoforged-docs-previews.pages.dev

### CODE REVIEW

**Comment by ChampionAsh5357** [comment]
Why not do it for all the pages which have the issue?

**Comment by srcres258** [comment]
> Why not do it for all the pages which have the issue?

Only found this one by accident when reading the documentation. If needed I can check all pages to discover similar issues.

**Comment by ChampionAsh5357** [comment]
Please do and thanks. There's only a few more instances based on a quick search.

**Comment by srcres258** [comment]
> Please do and thanks. There's only a few more instances based on a quick search.

OK, I'll work on then.

**Comment by srcres258** [comment]
All documentation files have been checked and fixed up targeting the same issue.

**Pull request merged**
