### PR TITLE
update capability documentation for planned refactor

### PR DESCRIPTION
**Pull request by agnor99**
Updates the capability documentation to match the capability refactor https://github.com/neoforged/NeoForge/pull/73
I try to keep parity to the PR if further changes happen.

------------------
Preview URL: https://pr-13.neoforged-docs-previews.pages.dev

### CODE REVIEW

**Comment by ChampionAsh5357** [comment]
I'm assigning myself so I can keep track of this. Request a review whenever you want me to take a look in its current state. This should probably be a draft until it gets merged.

**Comment by agnor99** [comment]
I'll probably reword and add a few things here and there (like the BlockCapabilityCache), but I would like to get an opinion: Where should the Capabilities Page go? It's currently under the data storage category, even though caps don't do that anymore. Should the page stay there to keep links working? Or which category should the page be put under?

**Comment by ChampionAsh5357** [comment]
It's probably better to rename the entire section since caps, attachment data, and saved data are roughly the same category in my mind. Maybe something like 'extensions'?

**Comment by agnor99** [comment]
I've decided against the rename of the group to extensions, because that would exclude Codecs from the group and would clash with the Concepts of Extension Interfaces that are added by Neo

**Comment by ChampionAsh5357** [comment]
Closing because of #34. Thank you for the work so far though!

**Pull request closed without merging**
