### PR TITLE
Add Chinese translation for NeoForged and NeoGradle documentation

### PR DESCRIPTION
**Pull request by srcres258**
Add Chinese translation for NeoForged and NeoGradle documentation to make convenience for developers in China's Minecraft mod community.

------------------
Preview URL: https://pr-18.neoforged-docs-previews.pages.dev

### CODE REVIEW

**Comment by ChampionAsh5357** [comment]
Thank you for your work on the translation!

Apologies, but we currently don't have a team in place to review this PR with any degree of accuracy or the ability to maintain if it gets merged. We could use a translation app, but we would prefer having native speakers review PRs for accuracy.

As a heads up, until the teams and proper structure are in place, this PR likely won't be reviewed. Until then, you are welcome to keep translating.

**Comment by srcres258** [comment]
> Apologies, but we currently don't have a team in place to review this PR with any degree of accuracy or the ability to maintain if it gets merged. We could use a translation app, but we would prefer having native speakers review PRs for accuracy.

It doesn't matter. I'll keep this PR as a draft until reviewing process is available.

**Comment by Mysterious-Dev** [comment]
Maybe we can set up a Crowdin for translations of the documentation (and maybe the website).This would allow NeoForge projects to be translated with a more “user-friendly” interface.

**Comment by ChampionAsh5357** [comment]
The changes in Crowdin's API makes it no longer suitable for the needs of NeoForge, so we are currently looking into other systems.

**Comment by Matyrobbrt** [comment]
I would also argue that such systems aren't suitable for translating documentation, as documentation involves markdown, examples, and code comments. The best way of translating the docs is by translating the entire pages in an editor such as VSCode. More so, it would be harder to preview and update the translations in bulk if they're external to the repository.

On that note, this PR should organize the translations as explained in the [Docusarus docs](https://docusaurus.io/docs/i18n/introduction).

**Comment by srcres258** [comment]
> On that note, this PR should organize the translations as explained in the [Docusarus docs](https://docusaurus.io/docs/i18n/introduction).

OK, I'll reorganise the translations according to the standard mentioned.

**Comment by srcres258** [comment]
Rewritten in PR #19.

**Pull request closed without merging**
